---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  chart:
    spec:
      chart: tf-controller
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: tf-controller
      version: '>=0.2.5'
  interval: 1m0s
  releaseName: tf-controller
  values:
    replicaCount: 2

