apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: gcs-bucket
  namespace: flux-system
spec:
  interval: 30s
  url: ssh://git@github.com/snigdhasambitak/terraform-gcloud-demo
  ref:
    branch: main 
